### ISSUE TITLE
pdns 4.4.0>=: nsec params not accepted for non-dnssec setup

### ISSUE THREAD

**Issue by cherusk** [joeig/go-powerdns#18]
Getting this:

[2020-11-10T08:51:14.755Z] NSEC3PARAMs provided for **zone** 'de-muc.iaas.genesiscloud.net.', but zone is not DNSSEC secured.

For code stretch:
```
  name_server := fmt.Sprintf("%s.%s", primary_server_hostname, zone_domain)
        zone, err := pdns_api.Zones.AddNative(zone_domain,
                                              false,
                                              "",
                                              false,
                                              "",
                                              "",
                                              false,
                                              []string{ name_server })
```

Could you have a look? Should be trivial if skipping those params when dnssec bool is false, but not certain is it enough.

**Comment by joeig** [comment]
Hi!

I've tried to reproduce your issue without success. Furthermore, all tests against a real API endpoint succeeded.

I had to build PowerDNS 4.4.0-alpha3 (4 November 2020 12:21) first, because there hasn't been a stable authoritative server release for v4.4 so far. Can I ask you to try again with the latest version and share your results? Please make sure you're using the most recent build from [here](https://downloads.powerdns.com/releases/), or the Dockerfile from [this PR](https://github.com/joeig/docker-powerdns/pull/1) (like I did).

**Comment by cherusk** [comment]
Hi @joeig ,

that's the version we're running currently: version="4.4.0-0.alpha1.1pdns.el8"
It's coming from the CentOS8 EPEL official PowerDNS build and should be the most stable one can get currently for 4.4.

**Comment by cherusk** [comment]
Anyhow, it can be minor topic, I can catch it downstream until I'm in position to upgrade our PowerDNS release in the infra.
We can close here, down to your ilk.

**Comment by joeig** [comment]
Alright, that sounds reasonable. Thanks!
