### ISSUE TITLE
AddNative throws "invalid character"

### ISSUE THREAD

**Issue by AlessandroSechi** [joeig/go-powerdns#3]
Hello, 
using this code:

```golang
_, err := pdns.Zones.AddNative("example.org", false, "", false, "", "", true, []string{"localhost."})
if err != nil {
		fmt.Println(err)
	}
```

I have this error:

`invalid character '<' looking for beginning of value`

**Comment by joeig** [comment]
Which PowerDNS version are you running? You can try the [zone-operations](https://github.com/joeig/go-powerdns/blob/master/examples/zone-operations/main.go) example using a clean PowerDNS 4.1 instance created with `docker-compose up`.

**Comment by AlessandroSechi** [comment]
Thank you for your reply. 
I'm running PowerDNS 4.1.1. I found an error in my code, I fixed it, but now I have this error in the same call:

`Post http://<domainname>:<port>/api/v1/servers/localhost/zones: EOF`

Running a simple `curl` like the one proposed on PowerDNS API, on the same endpoint, example gives expected results.
What can I check?

**Comment by joeig** [comment]
This error usually occurrs when the peer immediately closes the connection instead of accepting the TCP payload, which, in this case, would be the HTTP `POST` request. Do you have some kind of reverse proxy or NAT router between Go and PowerDNS?

I was experimenting with the official `pdns-4.1.1-1pdns.el7.x86_64.rpm` package with sqlite3 backend and was able to execute the whole `zone-operations` example successfully. As soon as I stopped the `pdns_server` process, but kept the Docker container itself running, dockerd's network stack on macOS behaves as described above. In this situation, [I was able to reproduce](https://gist.github.com/joeig/808e8f17fc7b792e69ab396180769605) your observations.

You can verify this assumption by consulting Wireshark or tcpdump. For the time being, it's very unlikely that this issue can be resolved programmatically within this library.

**Comment by AlessandroSechi** [comment]
Solved! It was a misconfigured TCP reverse proxy causing the issue. Thanks
